version: "3.8"
services:
    client:
        volumes: 
            - /app/node_modules
            - ./client/:/app/
        build: 
            context: ./client
        ports:
            - "3000:3000"
    server:
        volumes:
            - /app/node_modules
            - ./server/:/app
        build: 
            context: ./server
        ports:
            - "8000:8000"
        depends_on:
            - mysql_db
    mysql_db:
        image: mysql
        environment:
            MYSQL_DATABASE: mohaji
            MYSQL_USER: user
            MYSQL_PASSWORD: Sesac1234*
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./server/db/mysql:/var/lib/mysql
            - ./db/utf8.cnf:/etc/mysql/conf.d/utf8.cnf
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        command: >
            bash -c "chmod 644 /etc/mysql/conf.d/*.cnf && /entrypoint.sh mysqld"
